### ISSUE TITLE
Reducing the size of the output built by dune

### ISSUE THREAD

**Issue by bhootd** [mnxn/promise_jsoo#4]
Following up on this thread: https://github.com/ocaml/dune/issues/4030#issuecomment-743990773

> I think it is the fault of promise_jsoo, it is linking the whole ppx stack: https://github.com/mnxn/promise_jsoo/blob/trunk/dune#L6

> Removing gen_js_api-ppx from the libraries field of promise_jsoo results in bg.bc.js of size 44K which seems about right.

Is there a scope to reduce the built output size?

**Comment by mlantas** [comment]
The latest release, 0.3.1, already stopped linking to `js_of_ocaml-ppx`, which significantly reduces the size of the generated JS (see https://github.com/mnxn/promise_jsoo/pull/3).


Building your [ff-webext-jsoo project](https://github.com/jayesh-bhoot/ff-webext-jsoo) with `dune build --profile release bg.bc.js` produces a 42 KB JS file for me.
