### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by smondet** [mnxn/promise_jsoo#6]
`promise_jsoo_lwt` is not on `opam` for instance.

**Comment by mlantas** [comment]
I hadn't realized I left unreleased changes for so long.

I'll need some time to review everything again to make sure the API changes are okay to release. 
The next release will be published within a week or 2.

**Comment by mlantas** [comment]
Version 0.4.0 has been released: https://github.com/mnxn/promise_jsoo/releases/tag/v0.4.0

You can track the new version's status on the opam repository here: https://github.com/ocaml/opam-repository/pull/25397

**Comment by mlantas** [comment]
Version 0.4.2 is now available on opam.

There were some problems with the opam packaging in 0.4.0 and 0.4.1, so those versions weren't published.
